# Auto-generated reescala calls
from pmp_sincro import reescala

def sincroniza_sin_TS(base_dir='./Input', segmento_ref='PI', segmento_target='M', offset_range=125, step_range=1):

    reescala(base_dir, "PMP1011", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1022", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1046", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1047", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1049", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1051", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1053", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1055", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1056", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1057", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1058", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1059", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1060", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1061", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1062", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1063", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1064", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1065", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1066", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1067", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1068", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1070", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1071", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1074", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1076", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1077", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1079", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1080", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1084", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1085", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1087", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1088", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1090", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1091", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1092", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1095", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
    reescala(base_dir, "PMP1097", segmento_ref, segmento_target, None, None, None, None, offset_range, step_range)
